version: "3"
name: short.live

services:
  redis:
    image: "redis:latest"
    ports:
      - "6349:6379"

  mongodb:
    image: mongo:latest
    container_name: short-url-mongodb
    ports:
      - "27546:27017"

  timescaledb:
    image: timescale/timescaledb-ha:pg16
    command: postgres -c max_wal_size=2GB
    environment:
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=shorte_events
    ports:
      - "5432:5432"
